#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    user: "1001:1002"
    # links:
    #    - redis:redis
    expose:
       - 8000
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000

#   redis:
#     image: redis:latest
#     expose:
#       - 6379

  nginx:
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./mysite/myapp/static:/static
    links:
      - web:web